[package]
name = "multiparty-signature-test"
version = "0.0.0"
edition = "2021"

[dependencies]
chacha20poly1305 = "0.10"
curve25519-dalek = "3"
hex = "0.4"
rand_core = "0.6"
sha2 = "0.10"
x25519-dalek = "1"

[[bin]]
name = "multiparty-signature-test"
