[package]
name = "test-oidc-provider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.2"
tokio = { version = "1.28", features = ["full"] }
jsonwebtoken = "8.3.0"
openssl = "0.10"
