name: Integration tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
env:
  RUSTFLAGS: -D warnings
  ACTIONS_STEP_DEBUG: true
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Relayer Docker Image
        run: |
          docker pull ghcr.io/near/pagoda-relayer-rs-fastauth
          docker tag ghcr.io/near/pagoda-relayer-rs-fastauth pagoda-relayer-rs-fastauth
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
      - uses: Swatinem/rust-cache@v2
      - name: Bootstrap Rust Docker cache
        run: |
          mkdir -p target/{docker-cache-build-target,docker-cache/usr/{local/cargo,src/app}}
          cd target
          echo "target:"
          ls
          echo "docker-cache-build-target:"
          ls docker-cache-build-target
          du -sh docker-cache-build-target
          mv docker-cache-build-target docker-cache/usr/src/app/target
          rsync -avzh --ignore-missing-args \
            ~/.cargo/{bin,git,.crates.toml,.crates2.json,registry/{cache,index}} \
            docker-cache/usr/local/cargo
          tar -czC docker-cache -f docker-cache.tgz usr
          tar tf docker-cache.tgz
          echo "docker-cache.tgz:"
          du -sh docker-cache.tgz
          rm -r docker-cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: near/mpc-recovery:latest
          load: true
          cache-from: type=gha
          # cache-to: type=gha,mode=max
      - name: Export cargo artifacts from Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          target: export-artifacts
          outputs: type=tar,dest=target/docker-cache.tar
      - name: Integrate Rust Docker cache into Actions environment
        run: |
          tar -xvC ~/.cargo -f target/docker-cache.tar usr/local/cargo --strip-components=3
          mkdir -p target/docker-cache-build-target
          tar -xC target/docker-cache-build-target -f target/docker-cache.tar usr/src/app/target --strip-components=4
          rm target/docker-cache.tar
      # todo! revisit after prebuilt relayer images are available
      # - name: Test
      #   run: cargo test -p mpc-recovery-integration-tests --jobs 1 -- --test-threads 1
